# **Q.1)Program To implement arethmatic,relational,logical operator**

In [ ]:
n=int(input("Enter the number 1:"))
m=int(input("Enter the number 2:"))

sum=n+m
dif=n-m
mul=n*m

print(n>=m or n<m)
print(sum,dif,mul)

Enter the number 1:3
Enter the number 2:9
True
12 -6 27

# **Q.2)Program to check even or odd**

In [ ]:
n=float(input("Enter the number:"))
if(n%2==0):
  print("Even")
else:
  print("Odd")

Enter the number:4
Even

# **Q.3)Program to check greater of a)2 number b)3 number**

In [ ]:
a=int(input("Enter the number 1:"))
b=int(input("Enter the number 2:"))

if(a>b):
  print(a,"is greater")
elif(a<b):
  print(b,"is greater")
else:
  print("Equal")


a=int(input("Enter the number 1:"))
b=int(input("Enter the numvber 2:"))
c=int(input("Enter the number 3:"))

if(a>b and a>c):
  print(a,"is greater")
elif(b>a and b>c):
  print(b,"is greater")
elif(c>a and c>b):
  print(c,"is greater")

Enter the number 1:1
Enter the number 2:2
2 is greater
Enter the number 1:3
Enter the numvber 2:5
Enter the number 3:6
6 is greater

# **Q.4)Program to check wheter the number is prime or not**

In [ ]:
num=int(input("Enter the number:"))
if num > 1:
    # Iterate from 2 to n / 2
    for i in range(2, int(num/2)+1):
        # If num is divisible by any number between
        # 2 and n / 2, it is not prime
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

Enter the number:7
7 is a prime number

# **Q.5)Program to print all odd and even number sepratly**

In [ ]:
n=int(input("Enter the number"))
print("Even")
for i in range(n):
  if i%2==0:
    print(i)
print("Odd")
for i in range(n):
  if(i%2!=0):
    print(i)

Enter the number10
Even
0
2
4
6
8
Odd
1
3
5
7
9

# **Q.6)Program toi print all prime number in range.**

In [ ]:
start=int(input("Enter the start: "))
end=int(input("Enter the end: "))

for a in range(start,end+1):
    if a==1:
        continue
    for b in range(2,a):
        if a%b==0:
            break
    else:
        print(a)

Enter the start: 1
Enter the end: 20
2
3
5
7
11
13
17
19

# **Q.7)Program to find all reverse of number.**

In [ ]:
n=int(input("enter the number:"))
a=n
rev=0

while(a!=0):
  rem=a%10
  a=a//10
  rev=(rev*10)+rem
print("The reverse is:",rev)

enter the number:451
The reverse is: 154

# **Q.8)Check whether the number is palindrom or not**

In [ ]:
n=int(input("enter the number:"))
a=n
rev=0

while(a!=0):
  rem=a%10
  a=a//10
  rev=(rev*10)+rem
if(n==rev):
  print("Pallindrom")
else:
  print("Not Pallindrom")

enter the number:121
Pallindrom

# **Q.9)Check if number is armstrong or not**

In [ ]:
num=int(input("Enter the number: "))

s=0
a=num
while num!=0:
    rem=num%10
    num=num//10
    s+=rem**3
if s==a:
    print(a," is an armstrong")
else:
    print(a, "is not an armstrong")

Enter the number: 153
153  is an armstrong

# **Q.10)Print all armstrong in a given range**

In [ ]:
start=int(input("Enter the start: "))
end=int(input("Enter the end: "))

for a in range(start,end+1):
    b=a
    s=0
    while a!=0:
        rem=a%10
        a=a//10
        s+=rem**3
    if b==s: print(b)

Enter the start: 1
Enter the end: 200
1
153

# **Q.11)Program to find sum of n natural number**

In [ ]:
sum=0
n=int(input("enter the number:"))
for i in range(1,n+1):
  sum+=i
print(sum)

enter the number:5
15

# **Q.12)Program to find factorial of number**

In [ ]:
sum=1
n=int(input("enter the number:"))
for i in range(1,n+1):
  sum*=i
print("Factorial",sum)

enter the number:5
Factorial 120

# **Q.13)Program to fibonaci series**

In [ ]:
n=int(input("Enter n: "))

first=0;second=1
print(first)
print(second)
for a in range(n-2):
    third=first+second
    print(third)
    first,second=second,third

Enter n: 5
0
1
1
2
3

# **Q.14)Check wether an year is a leap year or not**

In [ ]:
year=int(input("Enter the year: "))

if year%4==0:
    if year%100==0:
        if(year%400==0):
            print(year, "is a leap year")
        else:
            print(year, "is not a leap year")
    else:
        print(year, "is a leap year")
else:
    print(year, "is not a leap year")

Enter the year: 2004
2004 is a leap year

# **Q.15)Convert into celcius/Farenheight**

In [ ]:
temp=float(input("Enter the temperature in Celsius: "))
print("Temperature in Fahrenheit is: ",((9/5)*temp)+32)

temp2=float(input("Enter the temperature in Fahrenheit: "))
print("Temperature in Celsius is: ",((temp2)-32)*(5/9))

Enter the temperature in Celsius: 45
Temperature in Fahrenheit is:  113.0
Enter the temperature in Fahrenheit: 113
Temperature in Celsius is:  45.0

# **Q.16)Print Factors of number using function**

In [ ]:
def fac(n):
  for i in range(1,n+1):
    if(n%i==0):
      print(i)
fac(5)

1
5

# **Q.17)Program to convert the number into decimal binary,ocatal formate using predefine function**

In [ ]:
n=int(input("Enter the number:"))
print(bin(n))
print(hex(n))
print(oct(n))

Enter the number:5
0b101
0x5
0o5

# **Q.18)Find fibonaci series of number using function**

In [ ]:
n=int(input("Enter n: "));

first,second=0,1;
print(first);
print(second);
def fibo(f,s,n):
    if(n==0):return;
    t=f+s;
    print(t);
    f,s=s,t;
    n=n-1;
    fibo(f,s,n);
fibo(first,second,n-2);

Enter n: 5
0
1
1
2
3

# **Q.19)Find factorial of number using function.**

In [ ]:
def f(n):
  p=1
  for i in range(1,n+1):
    p*=i
  print(p)
f(5)

120

# **Q.20)Find Factorial of number using recursion**

In [ ]:
def f(n):
  if(n==1):
    return n
  else:
    return n*f(n-1)
a=f(5)
print("Factorial using recursion:",a)

Factorial using recursion: 120

# **Q.21)Sum of first n number using recustion**

In [ ]:
n=int(input("Enter n: "));

def func(n):
    if n==1: return n;
    return n+func(n-1);
print("Sum of first",n,"natural numbers is:",func(n));

Enter n: 5
Sum of first 5 natural numbers is: 15

# **Q.22)Program to convert decimal into binary**

In [ ]:
def b(n):
    if(n==1):
        return "1"
    else:
        r=n%2
        return b(n//2)+str(r) 
c=4
a=b(4)
print("The binary representation of",c,":",int(a))

The binary representation of 4 : 100

# **Q.23)Program to display power of 2 using Lamda Function**

In [ ]:
n=int(input("Enter the power to obtain:"))
a=lambda b: 2**b
for i in range(n+1):
    print(a(i))

Enter the power to obtain:5
1
2
4
8
16
32

# **Q.24)Program to find area of triangle,cylender,circle using Lamda Function**

In [ ]:
l=int(input("Ente the length:"))
b=int(input("Enter the breath:"))
r=int(input("enter the radius:"))
h=int(input("Enter the height:"))
a1=lambda l1,b1:l1*b1
a2=lambda l1,b1:0.5*l1*b1
a3=lambda r1,h1:3.14*r1*r1*h1
print("Rectangle:",a1(l,b))
print("Triangle:",a2(l,b))
print("Cylender:",a3(r,h))

Ente the length:3
Enter the breath:6
enter the radius:2
Enter the height:1
Rectangle: 18
Triangle: 9.0
Cylender: 12.56

# **Q.25)Write a Program to add 2 matrice**

In [ ]:
a=[]
a1=[]
sum=[]
n=int(input("Enter the row:"))
m=int(input("Enter the col:"))
print("Matrice 1")
for i in range(n):
    l=[]
    for j in range(m):
        p=int(input("Enter the number:"))
        l.append(p)
    a.append(l)
print("Matrice 2")
for i in range(n):
    l1=[]
    for j in range(m):
        p1=int(input("Enter the number:"))
        l1.append(p1)
    a1.append(l1)

for i in range(n):
    l2=[]
    for j in range(m):
        s=a[i][j]+a1[i][j]
        l2.append(s)
    sum.append(l2)
print("Matrice 1:",a)
print("Matrice 2:",a1)
for a in range(n):
    for b in range(m):
        print(sum[a][b],end=" ");
    print();

Enter the row:2
Enter the col:2
Matrice 1
Enter the number:1
Enter the number:2
Enter the number:3
Enter the number:4
Matrice 2
Enter the number:1
Enter the number:2
Enter the number:3
Enter the number:4
Matrice 1: [[1, 2], [3, 4]]
Matrice 2: [[1, 2], [3, 4]]
2 4
6 8

# **Q.26) Write a Program to multiply 2 matrice**

In [ ]:
m1=[]
m2=[]
m3=[]

col=int(input("Enter columns: "));
row=int(input("Enter rows: "));

for a in range(row):
    Col=[]
    for b in range(col):
        Col.append(int(input("Enter the element: ")));
    m1.append(Col);

for a in range(row):
    Col=[]
    for b in range(col):
        Col.append(int(input("Enter the element: ")));
    m2.append(Col);

for a in range(row):
    Col=[]
    for b in range(col):
        Col.append(0);
    m3.append(Col);

for a in range(row):
    for b in range(col):
        for c in range(row):
            m3[a][b]+=m1[a][c]*m2[c][b];

for a in range(row):
    for b in range(col):
        print(m3[a][b],end=" ");
    print();

Enter columns: 2
Enter rows: 2
Enter the element: 1
Enter the element: 2
Enter the element: 1
Enter the element: 2
Enter the element: 1
Enter the element: 2
Enter the element: 1
Enter the element: 2
3 6
3 6

# **Q.27)Write the transpose of a matrice**

In [ ]:
l=[]
t=[]
c=int(input("enter the collum:"))
r=int(input("enter the row:"))

for i in range(r):
  ls=[]
  for j in range(c):
    n=int(input("Enter the number in matrice:"))
    ls.append(n)
  l.append(ls)

for a in range(r):
    for b in range(c):
        print(l[a][b],end=" ");
    print();

for i in range(c):
  ls=[]
  for j in range(r):
    m=l[j][i]
    ls.append(m)
  t.append(ls)
print("Transpose of matrice:")
for a in range(len(t)):
    for b in range(len(t[0])):
        print(t[a][b],end=" ");
    print();

enter the collum:3
enter the row:2
Enter the number in matrice:1
Enter the number in matrice:2
Enter the number in matrice:3
Enter the number in matrice:4
Enter the number in matrice:5
Enter the number in matrice:6
1 2 3
4 5 6
Transpose of matrice:
1 4
2 5
3 6

# **Q.28)Program to find average in the List**

In [ ]:
l=[]
s=0
n=int(input("Enter the lenght:"))
for i in range(n):
    a=int(input("Enter the number:"))
    l.append(a)
for i in l:
    s+=i
print("Avg:",s/len(l))

Enter the lenght:3
Enter the number:1
Enter the number:2
Enter the number:3
Avg: 2.0

# **Q.29)Display various slice operation using list**

In [ ]:
lst=[15,2,3,44,25,6,17,8,9,10];

print(lst[:]);
print(lst[5:]);
print(lst[:7]);
print(lst[::2]);
print(lst[2:8:2]);
print(lst[-4:]);
print(lst[:-5]);
print(lst[-7:-2]);
print(lst[::-2]);
print(lst[-2:-7:-2]);
print(lst[-7:-2:2]);

[15, 2, 3, 44, 25, 6, 17, 8, 9, 10]
[6, 17, 8, 9, 10]
[15, 2, 3, 44, 25, 6, 17]
[15, 3, 25, 17, 9]
[3, 25, 17]
[17, 8, 9, 10]
[15, 2, 3, 44, 25]
[44, 25, 6, 17, 8]
[10, 8, 6, 44, 2]
[9, 17, 25]
[44, 6, 8]

# **Q.30)Program to illustrate various ways of concatination of List**

In [ ]:
l1=[2,3,4,5,7]
l2=[34,7,8]
r1=l1+l2
print(r1)
l3=[45,3,2]
l4=[67,8,9]
for i in l3:
  l4.append(i)
print(l4)


l5=[7,8,9]
l6=[65,32,11]
l5.extend(l6)

print(l5)

[2, 3, 4, 5, 7, 34, 7, 8]
[67, 8, 9, 45, 3, 2]
[7, 8, 9, 65, 32, 11]

# **Q.31)Program to find and count specific element in list**

In [ ]:
l=[1,2,3,4,5,1]
print(l.count(1))

print(l.index(3))

2
2

# **Q.32)Program to check for duplicate elements in list**

In [ ]:
l=[1,2,3,4,5,6,6]
f=1
for i in range(len(l)-1):
    a=l[i]
    for j in range(i+1,len(l)):
        if(a==l[j]):
            f=0
if(f==1):
    print("Non duplicates")
else:
    print("Duplicates")

Duplicates

# **Q.33)Program to iterate dictionary using for loop**

In [ ]:
n=int(input("Enter number:"))
d={}
for i in range(n):
    k=input("Enter the key:")
    v=int(input("Enter the value:"))
    d[k]=v
print(d)

Enter number:3
Enter the key:1
Enter the value:3
Enter the key:2
Enter the value:4
Enter the key:3
Enter the value:5
{'1': 3, '2': 4, '3': 5}

# **Q.34)Program to imlement nested dictionary**

In [ ]:
dict1={};

for i in range(3):
    key1=int(input("Enter key1: "));
    dict1[key1]={};
    key2=int(input("Enter key2: "));
    val=input("Enter value: ");
    dict1[key1][key2]=val;
print(dict1);

Enter key1: 1
Enter key2: 2
Enter value: 3
Enter key1: 4
Enter key2: 5
Enter value: 6
Enter key1: 7
Enter key2: 8
Enter value: 9
{1: {2: '3'}, 4: {5: '6'}, 7: {8: '9'}}

# **Q.35)Program to sort the dictionary by 1) keys 2) values**

In [ ]:
d={2:"Zakie",1:"Soham",43:"Tanishq",15:"Kartikey"}
sd={}
l=[]
sd1={}
k=list(d.values())
a=list(d.keys())
for i in sorted(a):
    sd[i]=d[i]

print(sd)

sk=sorted(k)


for i in sk:
    
    sd1[a[k.index(i)]]=i
    
print(sd1)

{1: 'Soham', 2: 'Zakie', 15: 'Kartikey', 43: 'Tanishq'}
{15: 'Kartikey', 1: 'Soham', 43: 'Tanishq', 2: 'Zakie'}

# **Q.36)Program to ilustrate diffrent set operation**

In [ ]:
s1={1,2,3,4,5}

s2={2,3,5,6,7,8}

print("The set s1:",s1)
print("The set s2:",s2)
print("The intersection of the 2 set is",s1.intersection(s2))
print("The union of the 2 set is",s1.union(s2))
print("Is s2 the disjoint of s1:",s1.isdisjoint(s2))

The set s1: {1, 2, 3, 4, 5}
The set s2: {2, 3, 5, 6, 7, 8}
The intersection of the 2 set is {2, 3, 5}
The union of the 2 set is {1, 2, 3, 4, 5, 6, 7, 8}
Is s2 the disjoint of s1: False

# **Q.37)Program to check whether a string is palindrom or not**

In [ ]:
def check(a):
  if(a==a[::-1]):
    return True 
  else:
    return False
s=input("enter the string:")
res=check(s)
if(res):
  print("String is Palindrom")
else:
  print("String is not Palindrom")

enter the string:mom
String is Palindrom

# **Q.38) Program to remove punctuations from a string**

In [ ]:
from string import punctuation
def rem(a):
  clean=""
  for i in a:
    if(i not in punctuation):
      clean=clean+i
  return clean

st=input("enter the string:")
st=rem(st)
print("The string after the removing punctuation:",st)

enter the string:zaki.e is' best
The string after the removing punctuation: zakie is best

# **Q.39)Program to sort a string in aphabatical order**

In [ ]:
s=input("Enter the string:")
l=[]
for i in s:
  l.append(i)
l=list(l)
l.sort()
srt_s="".join(l)
print(f"The {s} in a alphabetical order  is {srt_s}")

Enter the string:zakie
The zakie in a alphabetical order  is aeikz

# **Q.40)Program to count the number of vowel in a string**

In [45]:
s=input("enter the string:")
v=['a','e','i','o','u']
d={}
for i in s:
  if(i in v):
    if(i not in d):
      d[i]=1
    else:
      d[i]+=1
for i in d:
  print(f"{i}:{d[i]}")

enter the string:python is an simple language
o:1
i:2
a:3
e:2
u:1

# **Q.41)Program to check if a string is anagram or not.**

In [47]:
s=input("Enter the string 1:")

r=input("Enter the String 2:")
l1=[]
l2=[]
for i in s:
  l1.append(i)

for i in r:
  l2.append(i)

l1.sort()
l2.sort()
if("".join(l1)=="".join(l2)):
  print(f"{s} is an anagram of {r}")

Enter the string 1:zakie
Enter the String 2:akzie
zakie is an anagramof akzie

# **Q.42)Program to count the occurance of each word in a sentance**

In [50]:
sentance=input("enter the sentance:").split(" ")
d={}

for i in sentance:
  if(i not in d):
    d[i]=1
  else:
    d[i]+=1

for i in d:
  print(f"{i}:{d[i]}")

enter the sentance:python is one of the most useful languages in the world
python:1
is:1
one:1
of:1
the:2
most:1
useful:1
languages:1
in:1
world:1

# **Q.43)Program to reverse all the words in a given sentance**

In [55]:
class Sen:
  def __init__(self,s=""):
    self.s=s

  def r(self):
    l=self.s.split(" ")
    l=l[::-1]
    return " ".join(l)
n=input("Enter the sentance:")
s1=Sen(n)
result=s1.r()
print("The reverse of the given sentance:")
print(result)

Enter the sentance:python is one of the most useful languages in the world
The reverse of the given sentance:
world the in languages useful most the of one is python